# Site Settings
title: GetAssured for Business
email: hello@get-assured.co
description: Singapore’s first life insurance based employee benefits portal. We believe in helping you achieve a happier workforce without breaking the bank.
baseurl: ""
url: http://business.get-assured.co
twitter_username: getAssured
github_username:  getAssured
logo: /assets/images/get-assured-business-logo-white@3x.png
social:
    name: GetAssured for Business
    links:
      - https://www.linkedin.com/company-beta/13276163
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-time-to-read
exclude:
  - Gemfile
  - Gemfile.lock
